name: Build and tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - 'ubuntu:18.04'
          - 'ubuntu:20.04'
          - 'debian:stretch'
          - 'debian:buster'
          - 'debian:bullseye'
          - 'centos:7'
          - 'quay.io/centos/centos:stream8'
          - 'oraclelinux:8'
          - 'oraclelinux:9'

    name: Build on ${{ matrix.image }}
    container: ${{ matrix.image }}
    steps:

    # Dependencies ---------------------------------------------------------------------------
    - name: Install dependencies (Ubuntu/Debian)
      if: startsWith(matrix.image, 'ubuntu') || startsWith(matrix.image, 'debian')
      run: |
        apt-get update
        apt-get -y install git gcc g++ cmake make libxml2-dev liblz4-dev libzstd-dev
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Enable EPEL (CentOS)
      if: contains(matrix.image, 'centos')
      run: |
        yum -y install epel-release
    - name: Enable EPEL (Oracle Linux 8)
      if: contains(matrix.image, 'oraclelinux:8')
      run: |
        dnf -y install oracle-epel-release-el8
    - name: Enable EPEL (Oracle Linux 9)
      if: contains(matrix.image, 'oraclelinux:9')
      run: |
        dnf -y install oracle-epel-release-el9
    - name: Install dependencies (CentOS, Oracle Linux)
      if: contains(matrix.image, 'centos') || contains(matrix.image, 'oraclelinux')
      run: |
        yum -y install git gcc gcc-c++ cmake make libxml2-devel lz4-devel libzstd-devel

    # Checkout repository --------------------------------------------------------------------
    - uses: actions/checkout@v2

    # Build ----------------------------------------------------------------------------------
    # Note: Unit tests are disabled on CentOS7 due to outdated GCC version
    - name: Build the project
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=$TESTS
        make && make install
      env:
        TESTS: ${{ startsWith(matrix.image, 'centos:7') != true }}
    - name: Run tests
      if: startsWith(matrix.image, 'centos:7') != true
      run: cd build && make test
