name: Build RPM package

on: [push, pull_request]

jobs:
  rpm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ['centos:7', 'centos:8', 'fedora:28', 'fedora:29', 'fedora:30', 'fedora:31']

    name: Build on ${{ matrix.image }}
    container: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v1
    - name: Define global variables
      run: echo "::set-output name=zip_file::libfds-${IMAGE//:/}-$GITHUB_SHA.zip"
      env:
        IMAGE: ${{ matrix.image }}
      id: vars
    # Dependencies ---------------------------------------------------------------------------
    - name: Install dependencies (CentOS)
      if: startsWith(matrix.image, 'centos')
      run: |
        yum -y install epel-release
        yum -y install git gcc gcc-c++ cmake make libxml2-devel lz4-devel libzstd-devel rpm-build
    - name: Install depedencies (Fedora)
      if: startsWith(matrix.image, 'fedora')
      run: dnf -y install git gcc gcc-c++ cmake make libxml2-devel lz4-devel libzstd-devel rpm-build
    # Build ----------------------------------------------------------------------------------
    - name: Prepare for build
      run: mkdir build && cd build && cmake .. -DPACKAGE_BUILDER_RPM=On -DCPACK_PACKAGE_CONTACT="GitHub actions <no-reply@example.com>"
    - name: Build the RPM package
      run: cd build && make rpm
    - name: Pack RPM packages
      working-directory: 'build/pkg/rpm/rpmbuild'
      run: zip -r "$GITHUB_WORKSPACE/$ZIP_FILE" RPMS SRPMS
      env:
        ZIP_FILE: ${{ steps.vars.outputs.zip_file }}
    - name: Archive RPM packages
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.vars.outputs.zip_file }}
        path: ${{ steps.vars.outputs.zip_file }}
